// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Change: typeof import('./src/components/Change.vue')['default']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    P5Component: typeof import('./src/components/P5Component.vue')['default']
  }
}

export {}
